name = "JackGutts"
license = "MIT"
licenselink = "https://github.com/jngutteridge/hugo-jackgutts-theme/blob/master/LICENSE"
description = ""
homepage = "https://jackgutts.kingbrick.co.uk/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Jack Gutteridge"
  homepage = "https://jack.kingbrick.co.uk/"